# Generated by Django 3.2.3 on 2021-10-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemname',
            name='center_or_teacher_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='itemname',
            name='teaching_subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='itemname',
            name='image',
            field=models.ImageField(default='ishxismati.jpg', upload_to='item_img'),
        ),
    ]
