# Generated by Django 3.2.3 on 2021-10-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0003_auto_20211007_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemname',
            name='work_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
