# Generated by Django 3.2.3 on 2021-10-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0004_itemname_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemname',
            name='campany_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
