# Generated by Django 3.2.3 on 2021-10-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0005_itemname_campany_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemname',
            name='ijara_turi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
