# Generated by Django 3.2.3 on 2021-10-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0006_itemname_ijara_turi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemname',
            name='image',
            field=models.ImageField(default='ish.jpg', upload_to='item_img'),
        ),
    ]
