from django.urls import path
from .views import (
    About,
    AdsUpdateView,
    Contact_function,
    DeleteImg,
    FulldataUserView,
    FulldataView,
    HomeItemList,
    AddImagesView,
    AdsCreateView,
    HowTo,
    IjaraAdsCreateView,
    IjaraAdsUpdateView,
    ItemCreateView,
    ItemDeleteView,
    ItemUpdateView,
    OneUserAdsList,
    FilterByCategory,
    EduAdsCreateView,
    EduAdsUpdateView,
    ProductionCreateView,
    ProductionUpdateView,
    SearchList,
)

app_name = 'Ads'

urlpatterns = [
    path('', HomeItemList.as_view(), name='Home'),
    path('about/', About, name='About'),
    path('help/', HowTo, name='Help'),
    path('contact/', Contact_function, name='Contact'),
    path('search/', SearchList.as_view(), name='Search'),
    path('add/', ItemCreateView.as_view(), name='Add'),
    path('one/<pk>/', FulldataView.as_view(), name="Full"),
    path('oneads/<pk>/', FulldataUserView.as_view(), name="FullUser"),
    path('filter/<pk>/', FilterByCategory, name="Filter"),
    path('del/<int:pk>/', DeleteImg.as_view(), name="DelImg"),
    path('delete/<pk>/', ItemDeleteView.as_view(), name='Delete'),
    path('update/<pk>/', ItemUpdateView.as_view(), name='Update'),
    path('addimg/<int:pk>/', AddImagesView.as_view(), name="AddImg"),
    path('personalAds/', OneUserAdsList.as_view(), name='PersonalAds'),
    path('servise/add/', AdsCreateView.as_view(), name='AddWork'),
    path('servise/update/<pk>/', AdsUpdateView.as_view(), name='UpdateWork'),
    path('edu/add/', EduAdsCreateView.as_view(), name='AddEdu'),
    path('edu/update/<pk>/', EduAdsUpdateView.as_view(), name='UpdateEdu'),
    path('production/add/', ProductionCreateView.as_view(), name='AddProduction'),
    path('production/update/<pk>/',
         ProductionUpdateView.as_view(), name='UpdateProduction'),
    path('ijara/add/', IjaraAdsCreateView.as_view(), name='AddIjara'),
    path('ijara/update/<pk>/', IjaraAdsUpdateView.as_view(), name='UpdateIjara'),
]
